// Package llmdocs assembles the single source of truth for a CLI's LLM-facing
// reference: a directory of Markdown files embedded into the binary.
//
// The convention is one directory (typically internal/llmdocs) holding numbered
// Markdown files:
//
//	00-guide.md      hand-written orientation for the agent
//	10-auth.md       hand-written topic chapters
//	90-commands.md   generated by the catalog package via go generate
//
// Files are concatenated in ascending filename order, so the numeric prefix
// controls chapter order. Nothing else about the content is interpreted, other
// than the leading "# " heading which is used as the section title.
package llmdocs

import (
	"encoding/json"
	"fmt"
	"io/fs"
	"sort"
	"strings"
)

// Docs is a set of Markdown chapters rooted at dir inside fsys.
type Docs struct {
	fsys fs.FS
	dir  string
}

// Section is a single Markdown chapter.
type Section struct {
	File  string `json:"file"`
	Title string `json:"title"`
	Body  string `json:"body"`
}

// New returns the Docs rooted at dir inside fsys. dir is "." for an embed.FS
// declared with //go:embed *.md.
func New(fsys fs.FS, dir string) *Docs {
	if dir == "" {
		dir = "."
	}
	return &Docs{fsys: fsys, dir: dir}
}

// Sections returns every .md file under the root, ordered by filename.
func (d *Docs) Sections() ([]Section, error) {
	entries, err := fs.ReadDir(d.fsys, d.dir)
	if err != nil {
		return nil, fmt.Errorf("llmdocs: read %s: %w", d.dir, err)
	}

	names := make([]string, 0, len(entries))
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".md") {
			continue
		}
		names = append(names, e.Name())
	}
	sort.Strings(names)

	sections := make([]Section, 0, len(names))
	for _, name := range names {
		path := name
		if d.dir != "." {
			path = d.dir + "/" + name
		}
		data, err := fs.ReadFile(d.fsys, path)
		if err != nil {
			return nil, fmt.Errorf("llmdocs: read %s: %w", path, err)
		}
		body := strings.TrimRight(string(data), "\n")
		sections = append(sections, Section{
			File:  name,
			Title: titleOf(body),
			Body:  body,
		})
	}
	return sections, nil
}

// Markdown concatenates every chapter, separated by a blank line, with a
// trailing newline. This is what `<cli> llm` prints by default.
func (d *Docs) Markdown() (string, error) {
	sections, err := d.Sections()
	if err != nil {
		return "", err
	}
	bodies := make([]string, 0, len(sections))
	for _, s := range sections {
		if s.Body == "" {
			continue
		}
		bodies = append(bodies, s.Body)
	}
	if len(bodies) == 0 {
		return "", nil
	}
	return strings.Join(bodies, "\n\n") + "\n", nil
}

// JSON returns the chapters as an indented JSON array. This is what
// `<cli> llm --format json` prints.
func (d *Docs) JSON() ([]byte, error) {
	sections, err := d.Sections()
	if err != nil {
		return nil, err
	}
	if sections == nil {
		sections = []Section{}
	}
	return json.MarshalIndent(sections, "", "  ")
}

// titleOf returns the text of the first level-1 heading, or "" when the chapter
// has none.
func titleOf(body string) string {
	for _, line := range strings.Split(body, "\n") {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "# ") {
			return strings.TrimSpace(strings.TrimPrefix(trimmed, "# "))
		}
	}
	return ""
}
